### ISSUE TITLE
Side-by-side diff

### ISSUE THREAD

**Issue by hgezim** [extrawurst/gitui#1294]
**Is your feature request related to a problem? Please describe.**

Any interest in adding a side-by-side diff view?

**Describe the solution you'd like**

I'm a huge fan of GitUp but can't use it due to my code being on a remote (Linux) machine. Something like this would be great: https://github.com/git-up/GitUp#complete-example-2-gitdiff

**Comment by xJonathanLEI** [comment]
Would love split view of diffs too. This is especially helpful on larger screens.

**Comment by extrawurst** [comment]
For sure a thing planned. It will be something I want to tackle by getting rid of using the libgit2 based diffing and basically using a third party crate to do the diffing of arbitrary buffers. like for example difftastic or delta

**Comment by rootex-** [comment]
It would be also great to have ability to move small pieces of diff-code from right to left diff and vice-versa like IntelliJ IDEA does. Very convenient and very rare feature. 
Screenshot shows this (you can see arrows like >> and << for moving code):
![ij_compareFiles](https://user-images.githubusercontent.com/8237030/206687098-f7262ef1-38a6-4c9a-b960-7992a2c8afae.png)

**Comment by joyously** [comment]
I prefer side by side also. I use it here on GitHub.
![Minor refactors and deduplications by alexmaco · Pull Request 1411 · extrawurstgitui-07](https://user-images.githubusercontent.com/7957680/206753820-db6c9eb9-3449-4db4-82dd-dd18c13bb69f.jpg)

As for gitui providing an editor to merge from the diff, I think that's out of scope. It's not _that_ rare. Try Diffuse or Meld or Beyond Compare.

**Comment by zrock-dev** [comment]
Have you considered using delta for the side-by-side view?

I like a lot how it looks and I was wondering if is possible to integrate it, or if there is a way to use it with gitui.

https://github.com/dandavison/delta

**Comment by rootex-** [comment]
I've checked out delta and also created a feature request there. They offered to use gitui for this:
 
"Well, the description states that Delta is "a syntax-highlighting pager for git, diff, and grep output". It is not meant to change the code or to stage files. For that purpose, I would suggest [GitUI](https://github.com/extrawurst/gitui), which is also written in Rust."

Check the response here: https://github.com/dandavison/delta/issues/1305

**Comment by extrawurst** [comment]
@rootex- 

> Check the response here: [dandavison/delta#1305](https://github.com/dandavison/delta/issues/1305)

not sure what you are getting at? its cool it mentions gitui 👍

**Comment by rootex-** [comment]
> @rootex-
> 
> > Check the response here: [dandavison/delta#1305](https://github.com/dandavison/delta/issues/1305)
> 
> not sure what you are getting at? 

@extrawurst I meant a feature that allows to apply hunks in side-by-side diff view (e.g. to apply a hunk from the left pane to the right pane (IntelliJ IDEA UI uses arrow >> for this)), described in this thread:

> It would be also great to have ability to move small pieces of diff-code from right to left diff and vice-versa like IntelliJ IDEA does. Very convenient and very rare feature.
> Screenshot shows this (you can see arrows like >> and << for moving code):
> ![206753820-db6c9eb9-3449-4db4-82dd-dd18c13bb69f](https://user-images.githubusercontent.com/8237030/220381227-2fca2156-f29d-4812-9944-96b6261a9114.jpg)

Perhaps, I'd better create a separate feature request?

**Comment by extrawurst** [comment]
no need to create a separate ticket. providing a different way to visualise a diff will not change the ways it allows you to stage/unstage/reset changes in it

**Comment by cherio** [comment]
`vimdiff` already has a mature side-by-side diff implementation. Could it be leveraged? It comes with `vim` so it would be a pretty safe bet to assume it is already installed.

**Comment by ifnk** [comment]
What's the current status of this? Are there any recent updates?

**Comment by DianFanGuo2000** [comment]
Could you confirm if there are truly no updates available? This functionality is essential for code review purposes. The current diff interface in gitui significantly degrades the review experience, to the point where lazygit becomes a preferable alternative solely due to its support for delta-powered diff rendering.

**Comment by HigherOrderLogic** [comment]
> It comes with `vim` so it would be a pretty safe bet to assume it is already installed in a dev/server environment.

You cant assume this. Not every distro come with Vim pre-installed, and likewise, not all developers use `vim`.

Furthermore, I also would prefer if this feature is built directly into gitui itself and not relying on external tools.

**Comment by cherio** [comment]
> You cant assume this. Not every distro come with Vim pre-installed, and likewise, not all developers use `vim`.

They are call optional dependencies. When such a dependency is installed it usually adds a feature to the package that depends on it. This concept exists in virtually all distros.

**Comment by lamnguyenx** [comment]
I'm currently using LazyGit with a custom configuration in `~/.config/lazygit/config.yml` that binds Ctrl+G to display side-by-side diffs using git-delta:

```yaml
gui:
  theme:
    selectedLineBgColor:
      - reverse
os:
  copyToClipboardCmd: 'xclip -selection clipboard || tmux load-buffer -b 0 -'
customCommands:
  - key: '<c-g>'
    command: "git diff {{.SelectedFile.Name}} | delta --light --side-by-side --line-numbers"
    context: 'files'
    description: 'Open file diff in delta (side-by-side, eink-friendly)'
    output: terminal
  - key: '<c-g>'
    command: "git diff {{.SelectedCommitRange.From}}..{{.SelectedCommitRange.To}} | delta --light --side-by-side --line-numbers"
    context: 'commits'
    description: 'Side-by-side diff between selected commits (Diff Mode)'
    output: terminal
  - key: '<c-g>'
    command: "git diff {{.SelectedLocalCommit.Sha}}~1 {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}} | delta --light --side-by-side --line-numbers"
    context: 'commitFiles'
    description: 'Open file diff in delta (side-by-side, eink-friendly)'
    output: terminal
```

I'm wondering if `gitui` supports similar custom command bindings or external diff viewer integration, as I really appreciate gitui's performance and responsiveness.
