### ISSUE TITLE
UI bottom is unintelligible on WezTerm + Fish Shell + Catppuccin theme

### ISSUE THREAD

**Issue by gacallea** [extrawurst/gitui#2286]
**Describe the bug**

`gitui` bottom row of commands looks funny and unintelligible with WezTerm, Fish Shell, Catppuccin theme.

**To Reproduce**
1. Use WezTerm, Fish Shell, and gitUI with their own respective Catppuccin ports (Macchiato in my case but it's the same with other variants)

Relevant configs:

```toml
# wezterm.lua
[...]
config.default_prog = { "/opt/homebrew/bin/fish", "-l" }
config.color_scheme = "Catppuccin Macchiato"
[...]
```

```toml
# config.fish
fish_config theme choose "Catppuccin Macchiato"
alias gitui="gitui -t catppuccin-macchiato.ron"
```

**Expected behavior**
Clear and intelligible text

**Screenshots**

<img width="900" alt="Screenshot 2024-07-02 at 11 46 31 AM" src="https://github.com/extrawurst/gitui/assets/3269984/01034583-d1d7-4d72-8877-7747607ed73d">

**Context (please complete the following information):**
 - macOS 14.5
 - gitui nightly 2024-06-02 ()
 - rustc 1.79.0 (129f3b996 2024-06-10)

**Additional context**

- I am unsure where the problem lies
- using macOS native Terminal works fine. Even with `gitui -t catppuccin-macchiato.ron`
