### ISSUE TITLE
Add GitUI to Windows Package Manager

### ISSUE THREAD

**Issue by TheOnlyTails** [extrawurst/gitui#904]
Windows Package Manager (AKA Winget) is the new and official package manager for windows, and it'd be nice if we could install GitUI using it instead of chocolatey or other package managers.

See: https://github.com/microsoft/winget-cli

**Comment by extrawurst** [comment]
I would take a PR for that 👍

**Comment by TheOnlyTails** [comment]
Let me do some checking and find out!

**Comment by TheOnlyTails** [comment]
@extrawurst After looking at the various winget repos, I basically need 3 things from you:

- A unique package ID in the format `PublisherName.PackageName`
- The full name of the publisher, e. g. "Stephan Dilly"
- The full name of the package, e. g. "GitUI"

Afterwards, I can submit it myself to winget.

**Comment by TheOnlyTails** [comment]
I've generated an example manifest. Is this good?
```yaml
PackageIdentifier: StephanDilly.GitUI
PackageVersion: 0.17.1
PackageLocale: en-US
Publisher: Stephan Dilly
PackageName: GitUI
License: MIT License
ShortDescription: Blazing fast terminal UI for Git written in Rust
```
